import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface Match {
  id: number;
  home_team: string;
  away_team: string;
  format: string;
  venue?: string;
  match_date?: string;
}

interface Innings {
  innings_number: number;
  batting_team_name: string;
  total_runs: number;
  wickets_lost: number;
  overs_bowled: number;
  extras_total: number;
  batting: any[];
  bowling: any[];
}

interface ScorecardData {
  match: Match;
  innings: Innings[];
}

export const generateScorecardPDF = (data: ScorecardData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  let yPos = 20;

  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Cricket Match Scorecard', pageWidth / 2, yPos, { align: 'center' });
  yPos += 10;

  // Match details
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`${data.match.home_team} vs ${data.match.away_team}`, pageWidth / 2, yPos, { align: 'center' });
  yPos += 7;

  doc.setFontSize(10);
  doc.text(`${data.match.format}${data.match.venue ? ' • ' + data.match.venue : ''}`, pageWidth / 2, yPos, { align: 'center' });
  yPos += 5;

  if (data.match.match_date) {
    doc.text(new Date(data.match.match_date).toLocaleDateString(), pageWidth / 2, yPos, { align: 'center' });
    yPos += 10;
  } else {
    yPos += 5;
  }

  // Line separator
  doc.setDrawColor(220, 38, 38);
  doc.setLineWidth(0.5);
  doc.line(10, yPos, pageWidth - 10, yPos);
  yPos += 10;

  // Process each innings
  data.innings.forEach((innings, index) => {
    // Check if we need a new page
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }

    // Innings header
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(`${innings.batting_team_name} Innings`, 10, yPos);
    yPos += 7;

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(
      `${innings.total_runs}/${innings.wickets_lost} (${innings.overs_bowled.toFixed(1)} overs)`,
      10,
      yPos
    );
    yPos += 8;

    // Batting scorecard
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Batting', 10, yPos);
    yPos += 5;

    const battingData = innings.batting.map((batter) => [
      batter.name,
      batter.runs_scored || '0',
      batter.balls_faced || '0',
      batter.fours || '0',
      batter.sixes || '0',
      batter.strike_rate || '0.00',
      batter.dismissal_type || 'not out',
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [['Batter', 'R', 'B', '4s', '6s', 'SR', 'Dismissal']],
      body: battingData,
      theme: 'grid',
      headStyles: { fillColor: [220, 38, 38], fontSize: 9 },
      bodyStyles: { fontSize: 8 },
      columnStyles: {
        0: { cellWidth: 50 },
        6: { cellWidth: 40 },
      },
    });

    yPos = (doc as any).lastAutoTable.finalY + 10;

    // Extras
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Extras: ${innings.extras_total}`, 10, yPos);
    yPos += 8;

    // Bowling scorecard
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Bowling', 10, yPos);
    yPos += 5;

    const bowlingData = innings.bowling.map((bowler) => [
      bowler.name,
      bowler.overs_bowled || '0',
      bowler.maidens || '0',
      bowler.runs_conceded || '0',
      bowler.wickets || '0',
      bowler.economy || '0.00',
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [['Bowler', 'O', 'M', 'R', 'W', 'Econ']],
      body: bowlingData,
      theme: 'grid',
      headStyles: { fillColor: [220, 38, 38], fontSize: 9 },
      bodyStyles: { fontSize: 8 },
      columnStyles: {
        0: { cellWidth: 60 },
      },
    });

    yPos = (doc as any).lastAutoTable.finalY + 15;

    // Add separator between innings
    if (index < data.innings.length - 1) {
      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.3);
      doc.line(10, yPos - 5, pageWidth - 10, yPos - 5);
    }
  });

  // Footer
  const pageCount = doc.internal.pages.length - 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(150);
    doc.text(
      `Generated by Cricket Scoring App - Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
  }

  // Generate filename
  const filename = `${data.match.home_team}_vs_${data.match.away_team}_${new Date().toISOString().split('T')[0]}.pdf`;

  // Save the PDF
  doc.save(filename);

  return filename;
};
